### ISSUE TITLE
attribute ID "MIX" not unique?

### ISSUE THREAD

**Issue by hcrowley** [gem/gem_taxonomy#1]
The attribute ID “MIX” appears not to be unique as it is used twice, both in Table 2 (for Material of LLRS) and Table 6 (Occupancy)

**Comment by raoanirudh** [comment]
Propose to change the MIX entry in Table 2 (Material of the Lateral Load-Resisting System) to HYB (for Hybrid), and keep the MIX in Table 6 (Occupancy) unchanged to maintain its compatibility with previous versions of the GEM Taxonomy that are used in older exposure models.
